### PR TITLE
2nd attempt!

### PR DESCRIPTION
**Pull request by ghost**
Updated colours for Guest and Gift tables;
Re-arranged radio buttons on view and added pre-set values corresponding to response;
Added checkboxes to Gift table;
Signed-off-by:tyler-hlynsky tyler.hlynsky@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
Bah. I didn't pull from the Master and I think it's going to break on me like it did earlier...

**Comment by dbuhler** [comment]
Ugh. Unfortunately, there's a conflict because I made a change to the table creation for the guests view. Well, we can't fix this in time anymore, so let's just leave it for now and incorporate these changes next week.

**Comment by dbuhler** [comment]
And sorry for having interfered with you. Again. :-(

**Comment by ghost** [comment]
Dan's Interference: 
99.5% setting up and helping solve problems, .5% causing code conflicts (with a .4% margin of error)

Yeah, I'll add it in later.

**Comment by dbuhler** [comment]
This has been fixed with another pull request.

**Pull request closed without merging**
